### ISSUE TITLE
img

### ISSUE THREAD

**Issue by leibnizli** [leibnizli/RGB#1]
![RGB-App-Store](https://user-images.githubusercontent.com/1193966/169992576-3460712c-3800-4d5a-b636-ab9371835c6a.png)

**Comment by thunkli** [comment]
![rgb-logo](https://user-images.githubusercontent.com/1193966/72965935-8cb3d180-3df8-11ea-8551-bf9be0e36a3a.png)

**Comment by leibnizli** [comment]
![icon_128x128](https://user-images.githubusercontent.com/1193966/117617031-8c327c00-b19e-11eb-8265-43a8d1853a9f.png)
